### ISSUE TITLE
Stars background should not turn back on when clicking next button

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-player#35]
If stars was already turned off, it should not turn back on unless clicking the moon icon.

**Comment by leonidlewis** [comment]
I fixed this issue and pushed the code on dev-leo branch.
Please review the code and let me know
Thank you.

**Comment by keybrdist** [comment]
@leonidlewis please double check your work. It appears your changes did not produce the desired effect.   1.) Stars should be ON by default. Your version has Stars OFF by default.   I fixed this already but you can check your commit history if you like to verify what I'm saying. `git checkout 8fa48173da7893d013e4f1732603fb6144e2b1f2` and then run the project on your local and you will see stars are off by default.   Once again, you do not need to do anything. I have already fixed the issue and this ticket is now closed.

**Comment by leonidlewis** [comment]
Thank you for your work and advice.
