### ISSUE TITLE
Need to reduce overall package size

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-player#37]
Use Vue package analyzer to find ways to reduce the overall package size. 

Goal is to speed up 1st load times for new visitors.

**Comment by keybrdist** [comment]
@leonidlewis are you familiar with using Package Analyzer to optimize node modules?

**Comment by leonidlewis** [comment]
I previously utilized webpack-bundle-analyzer to optimize the node_modules in my project. With your permission, I'd like to attempt to optimize the current project now
