### ISSUE TITLE
Image not appearing on first load.

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-player#38]
Problem: When you loda https://dnbradio.com/player for the first time it does not display the radio image.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/3534206/231038488-033831c3-0e64-4a8b-bd1d-9363d3df50c3.png">

Expected Result:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/3534206/231038649-0ca02ba5-d12a-4d94-a032-7388182fd1a8.png">

**Comment by leonidlewis** [comment]
I have not encountered any issues when running the project, and the expected screen always appears. Could you please provide me with the steps to reproduce the issue you are experiencing?
This is my screen when I meet the project on the web at first time.
![image](https://user-images.githubusercontent.com/83287135/231269239-6c9975b6-b725-4922-b8b4-322e472d8d8d.png)

**Comment by keybrdist** [comment]
It seems to be ok now. Closing this issue for now.

**Comment by leonidlewis** [comment]
I fixed the code
