### ISSUE TITLE
calendar page is showing HTML tags in preview text

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-player#42]
Problem: `<br />` is appearing in the show title on each calendar entry. 
Expected behavior. An actual line break should be shown if possible (or strip the HTML so it doesn't appear if you cannot make line break work).

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/3534206/232912026-cde9461d-4121-4b02-9353-6a4e5c5b879b.png">

**Comment by leonidlewis** [comment]
I already fixed this issue. However when I click on a single date slot in the calendar, I encounter an error. Could you please confirm whether you are also experiencing this issue on your end?

**Comment by keybrdist** [comment]
Issue is resolved!
