### ISSUE TITLE
Playback should auto-recover on event, net::ERR_NETWORK_CHANGED

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-player#55]
Problem: Playback stops when net::ERR_NETWORK_CHANGED happens
<img width="847" alt="image" src="https://github.com/dnbradio/dnbradio-player/assets/3534206/f5a7f567-ccce-48bf-b95c-ce68d1f2e1df">

Expected Result: Playback should retry once NET connectivity is re-established.

**Comment by keybrdist** [comment]
Testing: You can test this by switching wifi connection to Wired or switching between multiple wifi connections. 

Expected result: the player should catch these events and retry after x seconds until it receives a connection.

**Comment by keybrdist** [comment]
@leonidlewis please check this one

**Comment by leonidlewis** [comment]
Let me fix it
