### ISSUE TITLE
Now playing titles are showing \' in the title (escaped chars)

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-player#9]
Screenshot:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/3534206/227788317-a8d9eeae-e547-41e2-982a-9b55e8982a36.png">

**Comment by keybrdist** [comment]
This is an issue caused by double-escaped characters.   We need to fix this on the UI side. See "He Can\\'t" in the above screenshot. This should say "He Can't". Please replace all \\' with just ' on the artist and title rows.

**Comment by leonidlewis** [comment]
I fixed this issue just adding the decodeURIcomponent() method in javascript.
